name: Generate Kindle Image
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows you to run it manually

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Take Screenshot
        uses: swinton/screenshot-website@v1.x
        with:
          source: file://${{ github.workspace }}/index.html
          destination: dashboard.png
          width: 1264
          height: 1680

      - name: Commit and Push Image
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add dashboard.png
          git commit -m "Update dashboard image"
          git push
